# Generated by Django 4.1.2 on 2022-10-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('web_link', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='proj_images')),
            ],
        ),
    ]
