# Generated by Django 4.1.2 on 2022-10-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='web_link',
            new_name='web_url',
        ),
    ]
